### ISSUE TITLE
Recognizing existing projects

### ISSUE THREAD

**Issue by egoebelbecker** [kevboh/longform#120]
So, as I said below, I created a project on my Ubuntu laptop. This is after starting from scratch with a fresh plugin install and a project with a fresh Index.md.

I use Obsidian Sync. I went to macOS Monterey (never update before Apple gets to at least *.02) opened Obsidian, and install Longform. It sees no projects.

Console has this:

```
[Longform] Starting Longform 2.0.0…
node:internal/errors:464 Uncaught (in promise) TypeError: The "path" argument must be of type string. Received null
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1172:7)
    at e.getFullRealPath (app.js:1:1072141)
    at e.getFullPath (app.js:1:1072064)
    at app.js:1:1063785
    at n (app.js:1:1072467)
plugin:dataview:13951 Dataview: all 446 files have been indexed in 0.382s (446 cached, 0 skipped).
plugin:longform:35522 [Longform] Loaded and watching projects. Found 3 drafts in 0.422s.
node:internal/errors:464 Uncaught (in promise) TypeError: The "path" argument must be of type string. Received null
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1172:7)
    at e.getFullRealPath (app.js:1:1072141)
    at e.getFullPath (app.js:1:1072064)
    at app.js:1:1063785
    at n (app.js:1:1072467)
```
Here's the project index file:

```
---
longform:
  format: scenes
  title: The Great War of the Worlds
  workflow: Default Workflow
  sceneFolder: /
  scenes:
    - Chapter 1
    - Chapter 2
    - Chapter 3
    - Chapter 4
    - Chapter 5
    - Chapter 6
    - Chapter 7
    - Chapter 8
    - Chapter 9
    - Chapter 10
    - Chapter 11
    - Chapter 12
    - Chapter 13
  ignoredFiles: []
---
```

Here's data.json:

```
{
  "version": 3,
  "projects": {},
  "selectedDraftVaultPath": null,
  "userScriptFolder": null,
  "sessionStorage": "data",
  "sessions": [
    {
      "start": "2022-12-05T17:59:10.213Z",
      "total": 0,
      "drafts": {
        "GWOTW/The Great War of the Worlds/Index.md": {
          "total": 0,
          "scenes": {}
        },
        "1 - GWOTW/The Great War of the Worlds/Index.md": {
          "total": 0,
          "scenes": {
            "Chapter 1": 0,
            "Chapter 2": 0,
            "Chapter 3": 0,
            "Chapter 4": 0,
            "Chapter 5": 0,
            "Chapter 6": 0,
            "Chapter 7": 0,
            "Chapter 8": 0,
            "Chapter 9": 0,
            "Chapter 10": 0,
            "Chapter 11": 0,
            "Chapter 12": 0,
            "Chapter 13": 0
          }
        },
        "1 - GWOTW/Backup-Index.md": {
          "total": 0,
          "scenes": {
            "Chapter 1": 0,
            "Chapter 2": 0,
            "Chapter 3": 0,
            "Chapter 4": 0,
            "Chapter 5": 0,
            "Chapter 6": 0,
            "Chapter 7": 0,
            "Chapter 10": 0,
            "Chapter 11": 0,
            "Chapter 12": 0,
            "Chapter 13": 0
          }
        }
      }
    }
  ],
  "showWordCountInStatusBar": true,
  "startNewSessionEachDay": true,
  "sessionGoal": 500,
  "applyGoalTo": "all",
  "notifyOnGoal": true,
  "countDeletionsForGoal": false,
  "keepSessionCount": 30,
  "sessionFile": "longform-sessions.json",
  "numberScenes": false,
  "workflows": {
    "Default Workflow": {
      "name": "Default Workflow",
      "description": "A starter workflow. Feel free to edit, rename, or delete it and create your own.",
      "steps": [
        {
          "id": "strip-frontmatter",
          "optionValues": {}
        },
        {
          "id": "remove-links",
          "optionValues": {
            "remove-wikilinks": true,
            "remove-external-links": true
          }
        },
        {
          "id": "prepend-title",
          "optionValues": {
            "format": "$3{#} $1",
            "separator": "\n\n"
          }
        },
        {
          "id": "concatenate-text",
          "optionValues": {
            "separator": "\\n\\n---\\n\\n"
          }
        },
        {
          "id": "write-to-note",
          "optionValues": {
            "target": "manuscript.md",
            "open-after": true
          }
        }
      ]
    }
  }
}
```

On a potentially related note, I started this journey today because I have an Android tablet that is also failing to see the project.

**Comment by kevboh** [comment]
Did you mean to close this?

**Comment by egoebelbecker** [comment]
Yes. It was my mistake.
------
Eric Goebelbecker
***@***.***
https://ayne.ericgoebelbecker.com

------- Original Message -------
