### ISSUE TITLE
Forgetting all the scenes

### ISSUE THREAD

**Issue by aLahat** [kevboh/longform#212]
**Versions**
Longform version: 2.0.3
Obsidian version:
OS [e.g. macOS, Windows, iOS, Android]:  Win11
Theme:
Other plugins that you think might be relevant here:

**Describe the bug**
Every now and then all the scenes get forgotten,

I just open obsidian and there are no scenes. the index with the scenes are there, and so are the files, but it does not appear in the longform scene tab

**Comment by b-camphart** [comment]
That's troubling 😅  Couple questions:
1. When you say they're forgotten, what does it look like visually?
2. Can you think of any patterns around when this occurs?  Does it happen every time you open obsidian?  Or just under certain circumstances?

**Comment by aLahat** [comment]
Hi, it happens sometimes when I open Obsidian.It just looks like I have not started any longform project.   From: B. CamphartSent: 02 November 2023 14:36To: kevboh/longformCc: Albert Lahat; AuthorSubject: Re: [kevboh/longform] Forgetting all the scenes (Issue #212) That's troubling 😅 Couple questions:When you say they're forgotten, what does it look like visually?Can you think of any patterns around when this occurs? Does it happen every time you open obsidian? Or just under certain circumstances?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by beryllium** [comment]
I may be experiencing the same bug.

Obsidian 1.3.16 on macOS Sonoma (which I just recently upgraded to). Longform 2.0.4.

I have one multiscene story in progress, and at least one shortstory.

When I click the Longform icon in the icon bar, none of them show up.

<img width="337" alt="Screenshot 2023-11-10 at 11 12 32 PM" src="https://github.com/kevboh/longform/assets/602491/89012092-4b9c-4882-9cd2-e5f848a823e1">

I tried disabling all of my other installed plugins & restarting Obsidian, but that did not fix it.

Curiously, when I tried to disable the Longform plugin, I got a message saying 'Failed to unload Longform plugin'.

I opened the Developer Tools Console and saw this message on a fresh startup:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at ignoredPatternToRegex (plugin:longform:36334:41)
    at eval (plugin:longform:36281:64)
    at Array.map (<anonymous>)
    at StoreVaultSync.eval (plugin:longform:36281:53)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:longform:28:58)
```

When I tried unloading the Longform plugin, the 'Failed to unload' message correlated with this console message:

```
app.js:1 Plugin failure: longform TypeError: this.unsubscribeDraftsStore is not a function
    at StoreVaultSync.destroy (plugin:longform:35973:14)
    at LongformPlugin.onunload (plugin:longform:37708:29)
    at e.unload (app.js:1:716024)
    at e.<anonymous> (app.js:1:2037547)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at e.unloadPlugin (app.js:1:2037452)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.disablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
e.disablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1
```

Hopefully this helps.

**Comment by kevboh** [comment]
This does help, and seems like a bug. Do either of you have an `ignoredFiles` entry in your index files?

**Comment by kevboh** [comment]
@beryllium can you email me (kb@kevinbarrett.org) your entire index file, if you're comfortable doing so? That's probably the fastest way to reproduce this.

**Comment by etobias-musiced** [comment]
I might be having a similar issue -- I opened Obsidian this morning and longform was no longer recognizing a project. All of my files/scenes are visible in the folder that is used for the project 
![CleanShot 2023-11-20 at 09 52 40](https://github.com/kevboh/longform/assets/146162721/f8bea751-d4cc-4f40-bdde-b0991d1b069f)


and opening the the index file in Obsidian looks empty:

![CleanShot 2023-11-20 at 09 45 06](https://github.com/kevboh/longform/assets/146162721/13aa1039-abe4-4eed-98de-c83c14d24fb1)

Wen I looked inside the Obsidian folder on my computer and opened the index file the file contained all of the information that should be there
![CleanShot 2023-11-20 at 09 45 35](https://github.com/kevboh/longform/assets/146162721/3d7d8c10-9c47-4934-a2d9-975a764282a1)

I tried closing out and re-opening Obsidian - did not change anything
restarted my computer and reopened Obsidian - did not change anything

I do have numerous ignored files that show up in the index file but none of them actually live in the project folder - I think they were all from file name changes that after getting updated Longform kept thinking the original file still existed. 

I manually deleted all of the text under ignored files in the index.md file and that did not change anything about the index file opening in obsidian as if nothing was in it other than the metadata

I then went into the "view sync version history" of the index file -- with the view sync version history I could see all of the information that was in the index.md file in the project folder that I opened outside of Obsidian - 

![SyncHistory](https://github.com/kevboh/longform/assets/146162721/cfd9a9ae-70e8-448f-8b43-c42912d6dbe2)

But when I attempted to restore that version Obsidian put up a message indicating that was the current version

When I used the "copy to clipboard" option and pasted all of the content into the index.md file in Obsidian the file now contained the information and when I went back to click on the longform plugin the project and all of the scenes were available again.


Any thoughts on how the index file opening within Obsidian and the same index file being opened outside of Obsidian were unsynced and if this could happen again?  A little nervous about continuing to use the plugin for this large project.

Luckily the version history was helpful in this case.  Sorry if this is in the wrong place in github - it seemed possibly related when I was looking for solutions this morning.

Thank you.

**Comment by bhrebec** [comment]
I'm having this issue as well. I do have a complicated sync setup, running mainly on windows 11 and syncing via icloud to an ipad. I've been thinking that's the underlying cause of it, but not 100% sure of that, or how it could possibly be happening, because everything else syncs just fine! The plugin seems to work perfectly while I'm using it on both devices, but it resets both scenes and ignoredFiles to empty arrays almost every time obsidian is restarted (but not every single time, sometimes it works correctly.)

Will attempt to reproduce a minimal test case without other plugins to see if I can give some actual useful information, will update if I find anything. I'm still kind of assuming that my goofy sync setup (folder junctions are involved) is my real issue here, but since others are having problems I thought I'd chime in.

In my case, the index file post-issue is literally just:

```
---
longform:
  format: scenes
  title: Test Note
  sceneFolder: /
  scenes: []
  ignoredFiles: []
---
```

If that helps in the slightest!

**Comment by etobias-musiced** [comment]
Just happened to me again - opened up my vault and Longform did not recognize that any longform project existed even though the folder still exists and the index file is there. The stability issue is a little scary - any ideas of what is happening?

**Comment by jgharding** [comment]
This is now happening to me regardless of sync, I can make a fresh test project, populate it with files etc, and as soon as I close and open Obsidian again all projects and scenes have vanished.

**Comment by kevboh** [comment]
Do you have errors in the developer console in Obsidian, and if so can you share them here?

It's not a stability issue, for what it's worth: you are not losing data (and Longform very purposefully does not store or alter notes in such a way that the changes can be easily lost). What happens when projects "disappear" is that an index file's `longform` property is invalid in some way, and Longform has lost track of it. It's still there on disk.

Fundamentally my hope is that the Obsidian team introduces more durable APIs for searching a vault by property. Right now it is error-prone, and very difficult to anticipate all the ways people's notes become malformed.

**Comment by kevboh** [comment]
@bhrebec it is almost certainly your sync setup; I'm not sure why, but it seems like your index file is being partially written (not by Longform, by icloud, maybe?) during sync, which causes the plugin to try and "fix" the index file. Not a lot I can do with sync issues, unfortunately, as I can't control what the file system does to files on disk.

**Comment by Nikko-A** [comment]
Hello! I seem to be having the same issue mentioned. Last thing that I could find that triggered this was that I closed Obsidian. No clue what happened.

**Comment by jgharding** [comment]
> Do you have errors in the developer console in Obsidian, and if so can you share them here?
> 
> It's not a stability issue, for what it's worth: you are not losing data (and Longform very purposefully does not store or alter notes in such a way that the changes can be easily lost). What happens when projects "disappear" is that an index file's `longform` property is invalid in some way, and Longform has lost track of it. It's still there on disk.

Yeah it's bizarre...I don't use the official Obsidian sync, it's just my files in Google Drive.

I've tried the three different methods of storing sessions too, and it seems to actually happen after the Android devices opens and closes Obsidian. Sometimes I open it, and suddenly some projects are there and some aren't too...

These are the errors that are popping up for me, it seems something is getting broken in the frontmatter? Odd that it mentions Kanban in the second error.

`
plugin:longform:36212 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'frontmatter')
    at StoreVaultSync.eval (plugin:longform:36212:26)
    at Generator.next (<anonymous>)
    at eval (plugin:longform:31:71)
    at new Promise (<anonymous>)
    at __awaiter (plugin:longform:27:12)
    at StoreVaultSync.resolveIfLongformFile (plugin:longform:36210:16)
    at eval (plugin:longform:35979:75)
    at Array.map (<anonymous>)
    at StoreVaultSync.eval (plugin:longform:35979:59)
    at Generator.next (<anonymous>)
    at eval (plugin:longform:31:71)
    at new Promise (<anonymous>)
    at __awaiter (plugin:longform:27:12)
    at StoreVaultSync.discoverDrafts (plugin:longform:35976:16)
    at LongformPlugin.watchProjects (plugin:longform:37894:29)
    at LongformPlugin.postLayoutInit (plugin:longform:37779:14)
    at t.<anonymous> (app.js:1:1983837)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at a (app.js:1:236081)
`

`
app.js:1 TypeError: Cannot read properties of null (reading 'format')
    at Object.checkCallback (plugin:longform:36702:26)
    at app.js:1:1773636
    at Array.filter (<anonymous>)
    at e.listCommands (app.js:1:1773574) 
   at e.getCommands (app.js:1:2372097)
    at t.getItems (app.js:1:2373140)
    at t.getSuggestions (app.js:1:1533151)
    at t.updateSuggestions (app.js:1:1532414)
    at t.onOpen (app.js:1:1532256)
    at t.onOpen (app.js:1:2372955)
    at e.open (app.js:1:1425669)
    at e.onOpen (app.js:1:2372027)
    at Oq (app.js:1:1772390)
    at e.executeCommand (app.js:1:1773923)
    at e.eval (plugin:obsidian-kanban:77:14406)
    at e.o [as executeCommand] (plugin:obsidian-kanban:23:77313)
    at e.onTrigger (app.js:1:1145316)
    at e.handleKey (app.js:1:743120)
    at e.handleKey (app.js:1:743233)
    at t.handleKey (app.js:1:743442)
    at e.onKeyEvent (app.js:1:744376)
`

**Comment by jgharding** [comment]
As a follow up, after I moved the projects file to a file in the vault it seems to be generally more stable.

on the occasions where all projects appear “gone”, closing and opening Obsidian fixes the error and they all return.

this seems to suggest it simply is not loading the sessions sometimes? They aren’t damaged, it’s just sort of skipping the file?

**Comment by kevboh** [comment]
Whoa, the kanban intersection is weird.

I'm going to push a small fix to handle obsidian cache misses, which I thought couldn't happen but I guess they can! I still don't think I can fix the actual root issue, however.

**Comment by kevboh** [comment]
see https://github.com/kevboh/longform/commit/617653515bdbe84d5c27a8d3b810302947e6883a

**Comment by kevboh** [comment]
I might close this (out of an abundance of hope?) in case this fixes it. Please comment if the next release with this in it (2.0.5) doesn't help!

**Comment by ProudBenzene** [comment]
@jgharding Hello, I wonder if your problem has been solved after the Longform updates? I've met just the same problem with you(ಥ_ಥ). Once I quit Obsidian and restart it, all my Longform projects were forgotten.

I use Syncthing to keep my Mac, iPad, Windows and Andriod devices synced, but I've added the longform profile into the ignored list:

```
.obsidian/plugins/longform/data.json
```

Yet, the problem still happens to me.

I've viewed my index.md in VSCode, and it seems that there were no problems with the format of yaml.

I really don't know how to solve the problem. Everytime I rewrited my projects into Longform and restarted Obsidian, my projects in Obsidian disappear again.

**Comment by kevboh** [comment]
The data.json file doesn't keep scene order and you should probably sync it.

How do you use syncthing to sync your iPad? I didn't think that was supported.

@ProudBenzene do you have an error in the console? Open developer tools and then restart Obsidian. If you see an error in red, share it here. That's the best way to dig into this sort of thing.

**Comment by kevboh** [comment]
@etobias-musiced what are you using to sync?

**Comment by kevboh** [comment]
To summarize, when this happens you should ideally collect and share with me, either here or privately:

1. The contents of the index file for any projects that seem off;
2. Any errors that might be present in dev tools;
3. If whatever you're using for sync has one, the sync log so I can look for index file conflicts;
4. Whatever you were doing right before this happened.

More broadly, there seem to be two issues at play here that end up looking similar but are very different. In the first, there's an error while loading the Longform plugin or parsing through index files, and that error causes projects to fail to load. They're all still there, the pane is just empty.

In the second, some combination of events causes Longform to think you have deleted scenes or moved them or edited the index file directly, and it attempts to correct the situation by updating the index file to reflect what it thinks is the reality of your vault—no scenes. Longform will always try to react to vault changes by keeping the index file up-to-date. Unfortunately, we have no way to know if sync is changing files around on disk vs. you making changes, and if sync is doing something weird like attempting to resolve conflicts by writing out an empty index file Longform can't really do anything about it. Ideally first-party sync would provide a hooks API to tell us when a file is about to updated via sync, or has a conflict, etc., but it does not—it all appears to be file system changes to Longform.

Anyway, if this happens again please try to provide the list above, either here or by email to kb@kevinbarrett.org. Thanks.

**Comment by kevboh** [comment]
It's also worth reiterating that your scenes themselves are not lost. I'm going to update the issue name to reflect this. Longform doesn't delete scene files automatically.

**Comment by kevboh** [comment]
Also @etobias-musiced I watched your video. It's a bit zoomed-in, so it's kind of hard to tell what's going on, but I think sync is breaking the index file's YAML frontmatter in some way. Also, when you copy-paste content into the index file it's not going to work how you think as those list items are not in the frontmatter. They have to be between the triple-dashes (`---`) in the `longform.scenes` value to be considered scenes. If you feel you must manually edit the index file it's best to do so in something like VSCode—Obsidian will struggle to handle the nesting. You sort of end up doing this at the end, but the YAML indentation is wrong. I can tell you're frustrated in the video, and appreciate it as a form of clarification, but the thing you end up creating in the index file isn't valid YAML and will break the plugin (even more than sync already appears to have broken it).

Are you editing the same Longform projects on two different machines simultaneously? Obsidian Sync is pretty naive: it's best to let it fully sync on one machine before touching any files.

**Comment by ProudBenzene** [comment]
> The data.json file doesn't keep scene order and you should probably sync it.
> 
> How do you use syncthing to sync your iPad? I didn't think that was supported.
> 
> @ProudBenzene do you have an error in the console? Open developer tools and then restart Obsidian. If you see an error in red, share it here. That's the best way to dig into this sort of thing.

Hello, sorry to get you back so late.

I use an app called [Mobius Sync](https://apps.apple.com/cn/app/m%C3%B6bius-sync/id1539203216) to help me sync things on iPad. It is almost perfect and costs 38 CNY.

Could you please tell me your email? I've recorded a screen of what happened and would like to send it to you. What's more, forgive me, I don't know which information in the console is what you need🥲 If you'd be happy to, could you tell me in detail exactly which part?

**Comment by kevboh** [comment]
@ProudBenzene kb@kevinbarrett.org. I also use syncthing (and mobius), and wasn't aware you could open obsidian vaults from it. Can you?

**Comment by ProudBenzene** [comment]
> @ProudBenzene [kb@kevinbarrett.org](mailto:kb@kevinbarrett.org). I also use syncthing (and mobius), and wasn't aware you could open obsidian vaults from it. Can you?

Yes, I can use mobius to sync the notes file to the Obsidian folder, very handy!

**Comment by wwjCMP** [comment]
After syncing, I encountered the same issue.

**Comment by drewlyton** [comment]
Hey friend, not to pile onto this but I'm also experiencing this issue when I close and reopen Obsidian. My index file loses most of my nested scenes and even if I restore a version of `Index.md` for my project that I know worked, it just overrides it again with the malformed and missing scenes.

**Comment by kevboh** [comment]
@drewlyton How do you sync?

**Comment by drewlyton** [comment]
> @drewlyton How do you sync?

I sync with Git

**Comment by drewlyton** [comment]
Okay, I was actually able to reproduce the same behavior by duplicating my vault on the same machine. Which makes me feel even more there's an internal state issue somewhere.

**Comment by kevboh** [comment]
This was still fascinating! Glad you found a fix. Your issue does lend some cred to my suspicion that this ends up being a result of the underlying sync system...

**Comment by harry-meadows** [comment]
I am having this issue as well. I'll attempt to walk through the documentation steps this weekend, but in short: 3 clients, Windows 10, OS X, and IOS using obsidian sync with every client set to sync all possible files, settings and plugins. Longform setup worked fine on windows machine, opened vault on mac and scene listings vanished on both machines. Recreating and importing scenes only works on one machine while obsidian is open. When it's restarted scene listings vanish again.

**Comment by harry-meadows** [comment]
1. Made new vault
2. installed longform, enabled
3. sync is off
4. created project folder and scenes folder
5. copy and pasted scenes from other vault into scenes.
6. restarted obsidian.
7. behavior so far is as expected.
8. output of index
	1. ---
longform:
  format: scenes
  title: test1
  workflow: Default Workflow
  sceneFolder: scenes
  scenes:
    - 1 The Party - Foundation
    - 1.1 Getting Ready
    - 1.2 Meeting Adam
    - 1.3 After the party Adam's view
    - Adams Christmas
  ignoredFiles: []
---

9. Setup obsidian sync and left vault open on mac.
10. restarted obsidian on mac, no issues.
11. restarted obsidian on pc, no scenes listed
	1. ---
longform:
  format: scenes
  title: test1
  workflow: Default Workflow
  sceneFolder: scenes
  scenes:
    - 1 The Party - Foundation
  ignoredFiles: []
---

<img width="761" alt="2024-03-23 09_23_49-Testing actions - longformtesting - Obsidian v1 5 11" src="https://github.com/kevboh/longform/assets/104517948/d608b64e-d489-4d99-99bf-b7af4731ec28">

**Comment by themadder** [comment]
Hiya, I don't move my vault around any which way, so I do not Sync in any which way, it stays just where it's at, just how it is, whenever I open obsidian and close obsidian.  
However I wanted to try LongForm, so I installed it and went to make a project and my Index files are consistently malformed, they appear with the strange property as others have shared above.  The file in the folder reveals it does have yaml formating, my question is, how do I fix this by making the yaml that is written in the Index.MD into Properties in my obsidian.  So my issue, the Index is never Indexing, and the sidebar routinely goes blank or I have duplicate links all to the same scene (ie, the list will appear 4 times, so there are 4 links to Scene2, that all lead to the same note).

I know very little, but my working theory is that Obsidian wants to read the properties, the fact that it can't read this wonky big one is the issue for me, so if I could split it into smaller properties, perhaps that would snatch together into a beautiful woven thread rather than a tangled knot.  I am thinking Format, Title, Workflow, would be Text or List Property, and sceneFolder would be text string?  Scenes and Ignored files would be List?
Because as I'm tryin to understand this right now, it's reading Longform as one singular property, whereas it has multiple properties within it.  Now I noticed my calendar doesn't do this with its properties, it has a lot of individualistic property settings, which has led to this theory.  I can use it with Aprils Automatic Timelines and we're dandy, they've all got their own properties, with prefixes that I can associate with each of them.  So, my fantasy calendar has fc-date property, fc-end property, and that can be read and included into the aat-timeline property, am I making sense?  But Longform seems to only want to read the current Longform property (which then contains these smaller parts).

My solution theory is that there needs to be lf-format, lf-title, lf-workflow, lf-scenefolder, lf-scenes, lf-ignoredfiles, and these individualistic properties would need to be read by the sidebar, but this theory firmly puts me outside of my depth.

And to repeat, I am not syncing my vault any which way, it stays basically locked onto this desktop home PC.  I have removed the synchronization issues from the problem and I still have the problem.

**Comment by kevboh** [comment]
It's not the shape of the frontmatter that is the issue. I suspect the content is malformed in some way. You can email me (kb@kevinbarrett.org) the index file or post it here. Usually it's a null or empty property.

**Comment by AleksVersus** [comment]
Hello, and sorry my bad english.

I see this problem, but I don't screened error in console.

My Index.md at time when truble is visibled^
`---
longform:
  format: scenes
  title: 09_folder_name
  workflow: Default Workflow
  sceneFolder: source
  scenes:
    - 00_head
  ignoredFiles:
    - 
---`
I look other index files and saw that IgnoredFiles was written differently. I fixed IgnoredFiles like this:
`---
longform:
  format: scenes
  title: 09_folder_name
  workflow: Default Workflow
  sceneFolder: source
  scenes:
    - 00_head
  ignoredFiles:
    - aaa
---`
Problem has gone.

**Comment by kevboh** [comment]
Yeah, just removed ignoredFiles entirely. The empty list there breaks parsing.

**Comment by robotfactory** [comment]
I had similar issues using the official Obsidian Sync where my projects would just not load in to the Longform pane. Removing the `ignoredFiles` field completely from my frontmatter resolved the issue. I was getting the same "can't read properties of null" mentioned [here](https://github.com/kevboh/longform/issues/212#issuecomment-1806730915)

**Comment by KunckelEDV** [comment]
I have the same issue. Obsidian Sync, edited an my phone, went to my Mac - empty. I followed the discussion on GitHub, checked my Index.md, and it contains all of my scenes in the korrekt order - in Longform (on the left) there are only some of them, and in no order. I started with "New scene", kopied a missing scene-name from my Index, pasted, return. Scene is there, complet with contend, but at the bottom of the Longform-list.
<img width="1112" alt="Bildschirmfoto von Obsidian am 02_09_2024, 13_51_11" src="https://github.com/user-attachments/assets/955c4b6c-0795-4757-a602-00047b3f9301">

**Comment by markmit1908** [comment]
I am accoutering this problem.  Using up to date Obsidian [1.7.4] and Longform [2.0.7].   Running on MacOS, IOS (iPad and iPhone) and windows.  Using Obsidian sync.

My observation is that the error is more common when i work on longford for a while. I suspect that something happens in the background and longform fails to save the new index file.  Index gets out of sync and the long form folder is lost. 

I cannot find a way to reconnect longform to the folder.  A single broken folder is enough to stop the adding from working with any of the folders in the ./Longform/ folder.

**Comment by schoonerbe** [comment]
Hi there - I am new to Obsidian and Long form but immediately have a similar issue.
Obsidian Vault is written by me and stored on my desktop
I have the official Obsidian Sync service and my vault is then synced
My boss who wants to use Longform has access to the remote vault, he does so 

When I use Obsidian my longform tab looks like this:
![Screenshot (5)](https://github.com/user-attachments/assets/13a31b4a-62fe-4a73-8951-1986b5fb05cf)

my files tab shows the named project with whatever my boss has added in Longform, in alphabetical order and without the Longform Goodies
![Screenshot (5)](https://github.com/user-attachments/assets/60f9d333-9e6a-40c2-9db0-3f28a7940b4d)


I do not understand how to correct this, if it works as intended, or if there is some greater issue but it greatly hampers our ability to work together on a synced vault using Longform

**Comment by Baysen** [comment]
I'll add myself to the list of people experiencing this. Also mixed use of MacOS and Windows with Obsidian Sync.
It mostly seems to happen on startup, which leads me to believe that Longform might be trying to scan for new scenes before Sync was able to update the index file. That would lead to it thinking there's new scenes and writing that error state to the index.
This would be a pretty important fix, since reordering scenes is pretty cumbersome in itself and it now happens almost every time I start Obsidian.

**Comment by KunckelEDV** [comment]
Hey, kevboh!
Thanks for answering. A temporary solution would be VERY helpful. 

Wolfgang

**Comment by Baysen** [comment]
I took a look and the problem likely isn't the index file syncing, but the file watchers detecting "new" scenes that are synced first before the index comes along. Haven't had the time to test it though.

A possible solution would be to set a (configurable?) timeout for those watchers on Obsidian boot

**Comment by KunckelEDV** [comment]
Looks promising!

Looking forward to using Longform again!

Wolfgang

**Comment by Baysen** [comment]
I took a shot at it. Have a look at the PR. I hope it makes sense, because it's been a while for me...

**Comment by Baysen** [comment]
@kevboh hey! Any chance you can take a look soon? If there's anything I can do/add/change just say the word. This is my first OSS contribution :)

**Comment by KunckelEDV** [comment]
I would love to. How do I get a new version of Longform?

Wolfgang

**Comment by kevboh** [comment]
> [@kevboh](https://github.com/kevboh) hey! Any chance you can take a look soon? If there's anything I can do/add/change just say the word. This is my first OSS contribution :)

Replied in PR, sorry for the delay.

**Comment by Baysen** [comment]
> In the PR [@kevboh](https://github.com/kevboh) said:
> "Fascinating. I need to think about this. Deeply integrating private API
> makes me nervous, but the promise is very compelling…"
> 
> I know using a private API makes you itchy (with good reason) but the
> plug-in is currently unusable for Sync users. Given that this is a popular
> alternative to standalone software like Scrivener I think it would help a
> lot of people.
> 
> Perhaps you can put the change behind a toggle with a warning. "Enabling
> this feature uses private APIs and may stop working without warning," or
> the like.
> […](#)

I added it to the settings with a description. Maybe I should add an extra warning as well to be safe?

**Comment by KunckelEDV** [comment]
Sorry to ask: How do I get a new version for testing? I am not familiar with Git and Pull Request and whatnaot.

Wolfgang

**Comment by Baysen** [comment]
> Sorry to ask: How do I get a new version for testing? I am not familiar with Git and Pull Request and whatnaot.
> 
> Wolfgang
> […](#)

If you don't know git, it's probably quite impossible. We'll have to wait for the approval of my PR

**Comment by Baysen** [comment]
My PR was merged, so you can give it a try now and see if it also fixes your problems.

**Comment by KunckelEDV** [comment]
Installed 2.10,

Sync ist finished, but Longform tells me „waiting for Sync to finish“, and thats that.

(On mobile)

Mit freundlichen Grüßen

Wolfgang Kunckel

--
Kunckel EDV Systeme GmbH · Elsasser Straße 31 · 28211 Bremen
Büroanschrift: Paul-Feller-Strasse 19 • 28199 Bremen
Tel: 0421-3499913 · Mobil: 0160-98777904 · http://www.kunckeledv.de/
Vertretungsberechtigter Geschäftsführer: Wolfgang Kunckel
Registergericht: Amtsgericht Bremen Registernummer: HRB 13733
Umsatzsteuer-Identifikationsnummer gem. § 27a UStG: DE114420037

Datenschutz: Wenn Sie Kontakt per Mail mit uns aufnehmen, dann sind Sie damit einverstanden, dass wir Ihre Daten für den angefragten Geschäftsvorfall solange speichern und nutzen, wie es den gesetzlichen Vorschriften entspricht. Beachten Sie hierzu auch das Recht auf Auskunft, Löschung, Sperrung in unserer Datenschutzerklärung.

‌Unsere allgemeinen Geschäftsbedingungen‌
Am 28. März 2025, 15:54 +0000 schrieb Baysen ***@***.***>:

**Comment by Baysen** [comment]
Mhh I can't reproduce it on Android

**Comment by KunckelEDV** [comment]
I am on iOS, latest version.

(Also on my iPad)

It does not go away, even restarting Obsidian, the iPad, its always spinning. Sync works perfekt, changes from one device is perfectly (and fast) symced. And the syncing indicator is solid green…



Mit den besten Grüßen

Wolfgang Kunckel

—
Elsasser Straße 31
28211 Bremen
+49 421 3499913
Mobil: +49160-98777904
Am 4. Apr. 2025, 17:45 +0100 schrieb Baysen ***@***.***>:

**Comment by Baysen** [comment]
Can you try deactivating the check for Obsidian Sync in plugin settings and just use the fallback wait time and see if that works?
